name: Upload dotnet package

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/DimSoftware/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - run: dotnet build --configuration Release DimSoft.Http/DimSoft.Http.csproj
      - name: Create the package
        run: dotnet pack --configuration Release DimSoft.Http/DimSoft.Http.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push DimSoft.Http/bin/Release/*.nupkg
